### ISSUE TITLE
Wrong balance on my account 

### ISSUE THREAD

**Issue by burslf** [eth-clients/sepolia#16]
I requested funds from faucets multiple times.
Etherscan has all my successful transactions, but when calling web3.eth.get_balance() of my address when connected to the Sepolia RPC I see a wrong value (0.23 Ether instead of 0.53 Ether - [see etherscan txs](https://sepolia.etherscan.io/address/0x102bb817b5acd75d3066b20883a2f917c5677777) )
Metamask also shows the wrong balance. 
I don't know where this could come from, if anyone could help, thanks

**Comment by Kuroshimacat** [comment]
I have same question, and I’m using iOS 16-MetaMask

**Comment by Cryptofowl** [comment]
Same issue. Fixed it by changing RPC endpoints from https://rpc.sepolia.dev, to https://sepolia.infura.io/v3/
