### ISSUE TITLE
 Can't add Sepolia to Metamask

### ISSUE THREAD

**Issue by koh-kaw** [eth-clients/sepolia#17]
Can't add Sepolia to Metamask.
Is this issue already known?

<img width="1199" alt="スクリーンショット 2022-08-16 12 11 54" src="https://user-images.githubusercontent.com/19935195/184790707-26d69ef9-99cf-4678-9c90-4c24c7fca5ea.png">
<img width="1176" alt="スクリーンショット 2022-08-16 12 14 26" src="https://user-images.githubusercontent.com/19935195/184790712-9dd2e6ef-4909-45dd-a259-f426b17161b6.png">
<img width="1148" alt="スクリーンショット 2022-08-16 12 14 38" src="https://user-images.githubusercontent.com/19935195/184790714-6e69238c-f8c8-4e64-a77f-c64c1a8ebc59.png">

**Comment by JustDaile** [comment]
I used this RPC: https://rpc.sepolia.org
and works fine.

**Comment by JustDaile** [comment]
![image](https://user-images.githubusercontent.com/7350920/184994682-cf18a2b7-bd4f-4844-9011-3a1da273ad3e.png)

**Comment by koh-kaw** [comment]
Thanks. it's works fine.
and can't buy Sepolia token in my environment. Is this correct?

**Comment by JustDaile** [comment]
You have request tokens from faucets. Here are two:
- https://faucet.sepolia.dev/
- https://sepolia-faucet.pk910.de/

**Comment by koh-kaw** [comment]
Many thanks!
