### ISSUE TITLE
Metamask can't connect: "Something Went Wrong"

### ISSUE THREAD

**Issue by coindegen** [eth-clients/sepolia#19]
I input the settings as specified in this repo, but Metamask still can't connect. It just spins out.

<img width="364" alt="image" src="https://user-images.githubusercontent.com/87461192/192300068-d445f43f-bd17-4c5b-9dcf-f4b28fec5d5a.png">

<img width="437" alt="image" src="https://user-images.githubusercontent.com/87461192/192300298-f96bbfca-fc46-4c3b-9c83-657182a7efc0.png">

All the other alternate RPCs give the same result.

**Comment by leandro-panigada** [comment]
Same error here. Any solution?

**Comment by leandro-panigada** [comment]
@maryam-fs the RPC url: https://rpc.sepolia.org works fine. 
Thank you!

**Comment by q9f** [comment]
Metamask now has native Sepolia support.
