### ISSUE TITLE
Bulk ETH on Sepolia

### ISSUE THREAD

**Issue by ViniciusTenenteSecurrency** [eth-clients/sepolia#21]
Hello, can you please provide me 10000 Sepolia ETH on 0x4C5F0f90a2D4b518aFba11E22AC9b8F6B031d204 ?

I'm currently working on some projects at Securrency that are really dependents of having ETH on some testnet so we can continue development.

Thank you!

**Comment by Prankyzz** [comment]
hi @ViniciusTenenteSecurrency  Seine people said that for now sepolia can replace like goerli for validators and others so please send 1000 sepolia for that sir so i don't have to look for goerli for now
0x9BDe91219DAb4a30B7151a5cc03cdeDb404804Ca
thank you appreciate!

**Comment by Prankyzz** [comment]
hi @eth2devops  some people said that for now sepolia can replace like goerli for validators and others so please send 1000 sepolia for that sir so i don't have to look for goerli for now
0x9BDe91219DAb4a30B7151a5cc03cdeDb404804Ca
thank you appreciate!

**Comment by q9f** [comment]
Sent

**Comment by Quinshant** [comment]
@q9f @eth2devops please send 3200 sepolia or some you can we want to set up a long term validator with Sepolia
0xC65048D555d3DbB9694bDd601cf7D89F995157B8
thank you whoever sent it
