### ISSUE TITLE
Request for SepoliaETH for ETHBrno² hackathon

### ISSUE THREAD

**Issue by burningtree** [eth-clients/sepolia#22]
The basic idea is described in the Goerli repository: https://github.com/eth-clients/goerli/issues/133

We are asking for a total of:

- **50 000 SepoliaETH**

Recipient: `0x6D639104757Cd7A3e4B649d9f8BeA6B204F49Cd6` (ethbrno.eth)

**Comment by q9f** [comment]
Sent

**Comment by burningtree** [comment]
> Sent

@q9f Herzlichen Dank! 🙏
