### ISSUE TITLE
Any public RPC websocket provider for Sepolia?

### ISSUE THREAD

**Issue by ViniciusTenenteSecurrency** [eth-clients/sepolia#24]
Hello, I need to run a huge amount of requests per day and was wondering if we have any public RPC websocket providers for Sepolia, do we?

Thanks!

**Comment by q9f** [comment]
Most commercial providers have RPC endpoints by now. Which one did you use for other testnets?

**Comment by ViniciusTenenteSecurrency** [comment]
I was working on others non-ethereum but evm compatible networks that provided me public and free RPC providers at least for testnets. On ethereum networks I usually go with Infura but it's expensive to run more than 2 millions requests a day with it, and it's still in test phase.

**Comment by q9f** [comment]
I don't think anyone can provide you with a free RPC for 2 million requests per day.
