### ISSUE TITLE
Request funds sepETH

### ISSUE THREAD

**Issue by dumpslabs** [eth-clients/sepolia#38]
please help send 2000 sepolia to test dapss and distribute to active users who are migrating this is very helpful thank you whoever gave it!
0xe6909A4D5c700A6996D76B1d294d29096B75f887

**Comment by xivanc** [comment]
I would be happy to get some Sepolia too in order to distribute to dapp devs and test users 0x91d8afa86b21446f3BD2043504aE13ABdcB0E59c . As well I'd be happy to provide a public Sepolia node for public goods.

**Comment by xivanc** [comment]
as promised above, here's a public Sepolia endpoint https://www.noderpc.xyz/rpc-sepolia/public
