### ISSUE TITLE
Uniswap V2 Factory contract on the Sepolia network

### ISSUE THREAD

**Issue by zikkuratti** [eth-clients/sepolia#47]
Someone got it ? share address or .sol code , appreciate

**Comment by minhthong21081999** [comment]
You can use it here:
UniswapV2Factory: https://sepolia.etherscan.io/address/0xc9f18c25Cfca2975d6eD18Fc63962EBd1083e978#code
ShushiswapV2Factory: https://sepolia.etherscan.io/address/0x5b8bDFd0e2274d507D7511a6f216c5E9F5cD07A1#code
