### ISSUE TITLE
https://faucet.sepolia.dev/ TLS cert is expired as of May 22, 23'

### ISSUE THREAD

**Issue by ElijahLynn** [eth-clients/sepolia#48]
Following up on this and intentionally creating a new issue and not just commenting on https://github.com/eth-clients/sepolia/issues/45, just so it gets more visibility/more noise. 

![image](https://github.com/eth-clients/sepolia/assets/1504756/04a52210-d7ec-4ecb-9bdc-7efb6c542a46)
![image](https://github.com/eth-clients/sepolia/assets/1504756/7695f668-4395-4eb7-bdc2-1467ae5b681a)

I'm going through the Mastering Ethereum book and it suggests the Ropsten Test Faucent to get test ETH into a wallet and we found that Ropsten is deprecated and that we should be using Sepolia, but Sepolia is deprecated as of May 22nd, 2023. 

https://github.com/ethereumbook/ethereumbook/issues/1033

**Comment by ElijahLynn** [comment]
In fact, if I click advanced, I can't even "visit anyways", so it is effectively down:

> You cannot visit faucet.sepolia.dev right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.
![image](https://github.com/eth-clients/sepolia/assets/1504756/2ec68dac-b528-46b5-882c-2472afd88c4d)

**Comment by ElijahLynn** [comment]
Here is the last issue where this happened, https://github.com/eth-clients/sepolia/issues/29, it looks like the certificate updating needs to be automated.

**Comment by Silur** [comment]
One month later :skull:

**Comment by q9f** [comment]
Whoever maintains it went dark and we cannot do anything about it.
