### ISSUE TITLE
Request Sepolia test

### ISSUE THREAD

**Issue by yagolgmesol** [eth-clients/sepolia#52]
Hi! We are team working on a new account abstraction bundler client implementation in python. We are missing 10000 sepolia ETH for a very long time to run a validator to get started in our work supporting the bundler to run in the alternative p2p mempool. 

I am unable to download the bridgeID app (not available in my country), and the faucets drips fractions of what we need. Please help :)
Recipient address : 0xfA80f7F84B66d56Fd622273899CD30B126852d4C

**Comment by q9f** [comment]
You cannot run validators on Sepolia, take a look at https://github.com/eth-clients/holesky

**Comment by yagolgmesol** [comment]
@q9f just found out about it but can you send it for testing apps and dapps for a very long time to our devs we really need it

**Comment by yagolgmesol** [comment]
5000-10000 it is invaluable for our long-term testing :) @q9f

**Comment by yagolgmesol** [comment]
pls help @q9f
