### ISSUE TITLE
request sepolia and Goerli Testnet funds.

### ISSUE THREAD

**Issue by thanh97** [eth-clients/sepolia#53]
Hello @pk910! Sorry for bothering you.

- I am running dapss on the Goerli network, I need an amount of native ETH tokens on the Goerli network to test the project.
- And I read ethereum's documentation that the Goerli Testnet will be shut down at the end of this year, and will migrate to the sepolia network. Can I get ETH on sepolia and prepare for the upcoming switch?

Can I get 5k ETH for Goerli network and 10k ETH for sepolia network?
Thank you very much!
**This is my master wallet address:**
0xaE456c40Cf4304528235a4f1c4522A25977Fd530

**Comment by yagolgmesol** [comment]
be careful, this is fake, this guy needs huge funds to sell don't send it to him! @pk910 @q9f

**Comment by pk910** [comment]
It's always the same when people don't provide a proper reason what they need these funds for...
I don't even try to verify it anymore 🤣
"run dapps" is basically the standard explanation everyone uses.. But there is really no need for thousands of eth for deployment 🤷‍♂️

**Comment by thanh97** [comment]
Oh! Can we sell ETH under testnet?
So maybe I know the reason why ETH testnet is so rare.
Actually for the ETH I request, I will distribute ETH under test net to users for a long time to attract potential customers. But if it is valuable ETH and not free ETH for developers then maybe I should stop this issue here.
Anyway, thank you so much for your feedback!

**Comment by pk910** [comment]
It should be free for everyone... That's actually the intention of having testnets.

Unfortunately there are lots of guys that abuse the goodwill of fund distributors / attack faucets etc to make testnet funds rare and valuable an can therefore sell their stack for own profit...
Too bad that this actually got kind of a business model and prevents us from distributing as easily as before :(
