### ISSUE TITLE
[CONCURRENCY_LIMIT] Only 1 concurrent sessions allowed per wallet address

### ISSUE THREAD

**Issue by satvikkalyan** [eth-clients/sepolia#64]
Hello, I'm getting the concurrent sessions error. Even though I'm not running any other sessions. Is there a way to get around this?

**Comment by pk910** [comment]
Heya @satvikkalyan,

The problem you refer to is probably related to the PoWFaucet.

Please head over to the [PoWFaucet](https://github.com/pk910/PoWFaucet) repository for faucet support or use one of the alternative faucets listed on https://faucetlink.to/sepolia.

**Comment by dufrenefetterw24** [comment]
I also encountered the same problem. When I use POW to faucet sep eth, it shows [CONCURRENCY_LIMIT] Only 1 concurrent sessions allowed per wallet address. What should I do? Is there any solution?

**Comment by parithosh** [comment]
Please move this issue to a more appropriate repository
