### ISSUE TITLE
Synchronization does not proceed. please help me!

### ISSUE THREAD

**Issue by junghyun0783** [eth-clients/sepolia#71]
I'm currently trying to run the Ethereum "sepolia" testnet, but initialization and synchronization are not working. I don't think it's a prysm problem.
Currently running through docker, the container creation command is as follows.

docker run -itd --name eth_testnet --log-opt max-size=10m --log-opt max-file=3 --network medalla -v D:\docker\container\testnet\eth\sepolia:/root -v D:\docker\container\testnet\eth\sepolia\.ethereumdata:/data -p 40021:8545 -p 40022:8546 -p 40023:30303/udp -p 40024:30303/tcp ethereum/client-go:v1.13.14 --sepolia --port 30301 --datadir "/data" --http --http.addr "0.0.0.0" --http.api admin,eth,debug,net,txpool,personal,web3,engine --http.vhosts "*" --http.corsdomain "*" --authrpc.addr "eth_testnet" --authrpc.port 8551 --authrpc.vhosts "*" --authrpc.jwtsecret /root/jwt_sepolia.hex --syncmode "snap" --snapshot=true

what's the problem?...
please help me!~

**Comment by junghyun0783** [comment]
Does this problem differ depending on the OS?
When running on Windows, it was not initialized.
But... currently, when I run it on Linux, the beacon is being initialized.

Was it an OS problem?
And now that the beacon node has been initialized, is the client node synchronized?

Currently, the client keeps showing a log saying "WARN [03-26|11:43:34.880] Post-merge network, but no beacon client seen. Please launch one to follow the chain!"

beacon
"[2024-03-26 11:44:15] INFO initial-sync: Processing block batch of size 64 starting from 0x61414545... 1280/4643321 - estimated time remaining 402h57m17s blocksPerSecond=3.2 peers=3
[2024-03-26 11:44:15] INFO initial-sync: Processing block batch of size 64 starting from 0xc9e9b282... 1344/4643321 - estimated time remaining 201h28m28s blocksPerSecond=6.4 peers=2"
Initialization is in progress.

Are my client nodes and beacon nodes currently operating normally?
Thank you for reading this long article.

**Comment by parithosh** [comment]
Please point your question to a relevant forum or ethstaker subreddit/discord. This repository is purely meant for storing testnet configs and not provide active support to users.
