### ISSUE TITLE
Requirement for Substantial Sepolia Quantities

### ISSUE THREAD

**Issue by BrunoBill** [eth-clients/sepolia#76]
Hello everyone,

I kindly request 9800 sepolia ETH to be sent to the following address: 0xd0A2E844A4DE367C6587b4612Da87a6e874Cd2Ca.

These funds are crucial for advancing security projects that heavily rely on having ETH on various testnets: L1 (ETH sepolia), L2 (ARB sepolia), and OP sepolia. Your assistance in this matter is greatly appreciated as it will facilitate the continued development of these projects.

Thank you for your support.

**Comment by BrunoBill** [comment]
Hi @q9f  pls!

**Comment by parithosh** [comment]
Please make the request in this repository instead: https://github.com/ethpandaops/fundingvault/
