### ISSUE TITLE
Sepolia faucet token

### ISSUE THREAD

**Issue by vncooking** [eth-clients/sepolia#77]
We're currently providing the Sepolia testnet faucet for users, allowing them to claim a minimum amount of tokens daily from the installed contract code.

Could you kindly allocate 15k ETH to sustain the faucet's operations?

Page faucet this here: [https://github.com/Uniswap/docs/issues/640](https://github.com/Uniswap/docs/issues/640)

You can directly interact with the contract at:
0x92438AAB163C33ff6E8cd46b11077712CEfeF9dD

Alternatively, you can transfer the funds to this wallet address:
0xe1E1ce7de2A0034499B0154Ef2f123f3DA136f72

Thank you so much!

**Comment by parithosh** [comment]
Please make the request in this repository instead: https://github.com/ethpandaops/fundingvault/
