### ISSUE TITLE
Sepolia Testnet Eth Request

### ISSUE THREAD

**Issue by le-sanglier** [eth-clients/sepolia#84]
Hello, my name is Taylor and I’m the CEO of Blocky.  We are building Delphi, a groundbreaking zero knowledge proof based EVM oracle system - https://www.blocky.rocks/delphi-oracle.  I’m requesting 10,000 Sepolia Eth to help us test our zkp onchain contracts.  The wallet address is 0x6801a745bd61B3F28962203538ecd3171E1Ab7B9.  The Sepolia Eth will be used by our developers to test the EVM components of our product.  This amount of Eth will enable our developers to move more quickly towards our launch as we have hit a bottleneck on what faucets can provide.

Thank you for your consideration.

**Comment by parithosh** [comment]
Please make the request in this repository instead: https://github.com/ethpandaops/fundingvault/
